# Generated by Django 2.2.7 on 2019-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooking_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
